[project]
name = "terraflex"
version = "0.4.3"
description = ""
authors = [{ name = "Elran Shefer" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.112.2,<1.0.0",
    "pydantic>=2.8.2,<3.0.0",
    "pydantic-settings>=2.4.0,<3.0.0",
    "httpx>=0.27.2,<1.0.0",
    "xdg-base-dirs>=6.0.1,<7.0.0",
    "typer>=0.12.5,<1.0.0",
    "pyyaml>=6.0.2,<7.0.0",
    "requests>=2.32.3,<3.0.0",
    "rich>=13.8.1,<14.0.0",
    "questionary>=2.0.1,<3.0.0",
    "semver>=3.0.2,<4.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.6.3,<1.0.0",
    "pytest>=8.3.2,<9.0.0",
    "anyio>=4.4.0,<5.0.0",
    "mkdocs-material>=9.5.34,<10.0.0",
    "mkdocs-include-dir-to-nav>=1.2.0,<2.0.0",
    "markdown-exec[ansi]>=1.9.3,<2.0.0",
    "mkdocs-include-markdown-plugin>=6.2.2,<7.0.0",
    "mkdocstrings[python]>=0.26.1,<1.0.0",
    "mkdocs-kroki-plugin>=0.9.0,<1.0.0",
    "pyright>=1.1.381,<2.0.0",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["terraflex*"]
exclude = ["docs_includes*"]

[project.scripts]
terraflex = "terraflex.cli.cli:main"

[project.entry-points."terraflex.plugins.storage_provider"]
git = "terraflex.plugins.git_storage_provider.git_storage_provider:GitStorageProvider"
local = "terraflex.plugins.local_storage_provider.local_storage_provider:LocalStorageProvider"
envvar = "terraflex.plugins.envvar_storage_provider.envvar_storage_provider:EnvVarStorageProvider"
onepassword = "terraflex.plugins.onepassword_storage_provider.onepassword_storage_provider:OnePasswordStorageProvider"

[project.entry-points."terraflex.plugins.transformer"]
encryption = "terraflex.plugins.encryption_transformation.encryption_transformation_provider:EncryptionTransformation"

[project.entry-points."terraflex.plugins.transformer.encryption"]
age = "terraflex.plugins.encryption_transformation.age.provider:AgeEncryptionProvider"

[project.entry-points."terraflex.plugins.dependencies"]
age = "terraflex.plugins.encryption_transformation.age.provider:AgeDependency"

[tool.ruff.lint]
select = [
    'F',      # Pyflakes
    'E',      # pycodestyle (Error)
    'I',      # isort
    'D',      # pydocstyle
    'UP',     # pyupgrade
    'YTT',    # flake8-2020
    'B',      # flake8-bugbear
    'T10',    # flake8-debugger
    'T20',    # flake8-print
    'C4',     # flake8-comprehensions
    'PYI006', # flake8-pyi
]
ignore = [
    'D105',
    'D107',
    'D205',
    'D415',
    'E501',
    'B011',
    'B028',
    'B904',
    'D100',
    'D101',
    'D102',
    'D103',
]
flake8-quotes = { inline-quotes = 'single', multiline-quotes = 'double' }
isort = { known-first-party = ['pydantic', 'tests'] }
mccabe = { max-complexity = 14 }
pydocstyle = { convention = 'google' }

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
'terraflex/cli/*' = ['T201']

[tool.pyright]
include = ["terraflex"]
exclude = ["**/node_modules", "**/__pycache__"]
strict = ["terraflex"]

executionEnvironments = [{ root = "." }]
