from typing import Protocol

from tfstate_git.server.base_state_lock_provider import LockBody


class StorageProviderProtocol(Protocol):
    def get_file(self, file_name: str) -> bytes | None: ...
    def put_file(self, file_name: str, data: bytes) -> None: ...
    def delete_file(self, file_name: str) -> None: ...
    def read_lock(self, file_name: str) -> bytes | None: ...
    def acquire_lock(self, file_name: str, data: LockBody) -> None: ...
    def release_lock(self, file_name: str) -> None: ...
